### ISSUE TITLE
unclear use of "latest release"

### ISSUE THREAD

**Issue by roeniss** [chriswalz/bit#14]
at [release page](https://github.com/chriswalz/bit/releases) `v0.4.19` seems latest version.

but when I type `curl -sf https://gobinaries.com/chriswalz/bit | sh` as README suggested, it downloaded `v0.5.4`.

Looks like at least one of them should be fixed -- changing the download link at gobinaries.com and/or changing latest release version

**Comment by chriswalz** [comment]
The way gobinaries.com works is it uses the latest tag which is v0.5.4. Which is the most current version. 

I was having some issues with goreleaser which is why the RELEASE Is behind. 

With that said I intend to use goreleaser as the primary means of releasing. 

Another important note is there are two binaries. It's unclear how to integrate with a sub package binary (/bitcomplete)

**Comment by roeniss** [comment]
you mean 0.5.4 is currently 'right' version to use? If so, why domt you make repo releasw version be 0.5.4

**Comment by roeniss** [comment]
(I dont intend to blame you @. Im just wondering whats going on lol)

**Comment by chriswalz** [comment]
We should. I can do it on Monday as I’m busy this weekend

**Comment by chriswalz** [comment]
I updated the release @roeniss
